### ISSUE TITLE
添加一个其他 好公司的table区域

### ISSUE THREAD

**Issue by codevvvv9** [godie996/contribution#2]
希望大家可以把觉得工作氛围不错的公司列出来，以便甄别公司的好坏、是否符合自己。

**Comment by zhmushan** [comment]
这不就变成赤裸裸的广告了么。。。。

**Comment by pangjunpeng** [comment]
![image](https://user-images.githubusercontent.com/27885402/51827315-0f0fcf80-2324-11e9-8043-e1360d496e51.png)

**Comment by jinrichardJIN** [comment]
@pangjunpeng 太秀了

**Comment by codevvvv9** [comment]
@zhmushan  没有啊，就是写出来让大家看看这些公司的工作状态，大家心里有数啊，也没啥硬广啊

**Comment by liushuaiQAQ** [comment]
![_20181123085935](https://user-images.githubusercontent.com/19658414/51882278-5a27f200-23b9-11e9-9611-7c4bf9ff4506.jpg)

**Comment by FrankFang** [comment]
你可以在 https://github.com/godie996/share/issues 提交公司名
