### ISSUE TITLE
anonymous（增加匿名分享渠道）

### ISSUE THREAD

**Issue by zhmushan** [godie996/contribution#4]
We need an anonymous channel to avoid the persecution of the company.

直接使用 GitHub 账号容易暴露自己的身份，遭到公司迫害，我认为应该增加一个匿名分享的频道。

**Comment by FrankFang** [comment]
好的

**Comment by noname2019** [comment]
https://github.com/godie996/share/issues/12
搞定……

**Comment by zhmushan** [comment]
Thx
