### ISSUE TITLE
996 

### ISSUE THREAD

**Issue by sad-wang** [godie996/contribution#6]
1. godie996公证恶厂加班行为此网站实名讨伐
2.既然都这样对你了 欢迎来到godie996互联网大型猎头平台 量身定制跳槽计划
3.菜是原罪 欢迎来到饥人谷增长才干

**Comment by FrankFang** [comment]
我不打算在 godie996 网站本身上公布公司信息，大家可以在 github 上提 issue，这样可以规避风险。
